### ISSUE TITLE
Infrastructure to embed PSScriptAnalyzer without keeping the code and binaries in the repository

### ISSUE THREAD

**Issue by ForNeVeR** [ant-druha/intellij-powershell#109]
The current source layout makes it harder to bundle PSScriptAnalyzer: we keep its releases right in the repo, at `language_host/current/LanguageHost/modules/PSScriptAnalyzer`. See #45 as a reference for how we currently update it.

Let's perform some Gradle magic to auto-download and unpack it, to make updates and management of the analyzer easier, and also remove any possible tampering with the binaries at our (or contributors') side.

## TODO
- [x] Download the binaries automatically
- [x] Make sure that the compatibility profiles aren't going back (see #113)
- [x] Add a validation of the plugin distribution size

**Comment by Omico** [comment]
I wrote something similar, see here. https://github.com/Omico/intellij-powershell/blob/e4c2f98d3f0b879ddd9572f70f908a0ca10d479c/build.gradle.kts#L109 

But now I prefer to move this part of the code into `build-logic` and get the new version through my project [Gradm](https://github.com/Omico/Gradm). 
A usage is looks like this https://github.com/Omico/Gradm/blob/main/build-logic/gradm/gradm.integration.github.yml
https://github.com/Omico/Gradm/blob/47a6a706115a9ebbe4254aac4f33013a4df1a8bc/build-logic/project/src/main/kotlin/gradm.root.gradle.kts#L19
